jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v3
        with:
          node-version: '18'  # match your project version

      - name: Install dependencies
        run: npm ci

      - name: Build Next.js
        run: npm run build

    # Continue deploy steps...